name: internship-bot

on:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  run:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: install deps
        run: pip install requests pandas beautifulsoup4 openpyxl python-dateutil

      - name: run bot
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}

        run: python internship_bot_v6.py
